server:
  port: 8081
spring:
  profiles:
    active: test
---
#测试环境
spring:
  profiles: test
  datasource:
    username: root
    password:  
    url: jdbc:mysql://127.0.0.1:3306/atcrowdfunding-v?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    #配置数据源  阿里  的druid  
    type: com.alibaba.druid.pool.DruidDataSource

    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
#   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
# 处理拦截器返回中文乱码
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
# 处理拦截器返回中文乱码
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
#       - classpath:department.sql
mybatis:
  # 指定全局配置文件位置
  config-location: classpath:mybatis/mybatis-config.xml
  # 指定sql映射文件位置
  mapper-locations: classpath:mybatis/mapper/*.xml
#文件上传
cbs:
    imagesPath: file:E:/img/
#=================================微信相关====================================
wxpay:
  #公众号
  appid: wx5beac15ca207cdd40c
  appsecret: 5548012f33417fdsdsdd6f96b382fe548215e9
#支付配置
#微信商户平台
  mer_id: 1503808832
  key: xdclasss20182018xdclass2018x018d
  #支付回调地址
  callback: 16web.tunnel.qydev.com/api/order/callback 



#微信开放平台配置(第三方登陆)
wxopen:
  appid: wx025575eac69a2d5b
  appsecret: deeae310a387fa9d3e8f3830ce64caac
  #重定向url
  redirect_url: http://16web.tunnel.qydev.com/api/v1/wechat/user/callback
#日志
#logging:
#  path: E:/img/
# 不指定路径在当前项目下生成springboot.log日志
# 可以指定完整的路径；
#logging.file=G:/springboot.log

logging:
  config: 
    classpath:logback-spring.xml 
  level:
    dao: debug
    org:
      mybatis: debug


---
#生产环境
spring:
  profiles: prod
  datasource:
    username: root
    password:  
    url: jdbc:mysql://127.0.0.1:3306/atcrowdfunding-v?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    #配置数据源  阿里  的druid  
    type: com.alibaba.druid.pool.DruidDataSource
#初始化鏈接池
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
#   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
# 处理拦截器返回中文乱码
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
# 处理拦截器返回中文乱码
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
#       - classpath:department.sql
mybatis:
  # 指定全局配置文件位置
  config-location: classpath:mybatis/mybatis-config.xml
  # 指定sql映射文件位置
  mapper-locations: classpath:mybatis/mapper/*.xml
#文件上传
cbs:
    imagesPath: file:E:/img/
#=================================微信相关====================================
wxpay:
  #公众号
  appid: wx5beac15ca207cdd40c
  appsecret: 5548012f33417fdsdsdd6f96b382fe548215e9
#支付配置
#微信商户平台
  mer_id: 1503808832
  key: xdclasss20182018xdclass2018x018d
  #支付回调地址
  callback: 16web.tunnel.qydev.com/api/order/callback 



#微信开放平台配置(第三方登陆)
wxopen:
  appid: wx025575eac69a2d5b
  appsecret: deeae310a387fa9d3e8f3830ce64caac
  #重定向url
  redirect_url: http://16web.tunnel.qydev.com/api/v1/wechat/user/callback
#日志
logging:
  config: 
    classpath:logback-spring.xml 
  level:
    dao: WARN
    org:
      mybatis: WARN
# 不指定路径在当前项目下生成springboot.log日志
# 可以指定完整的路径；
#logging.file=G:/springboot.log
